{{- if .Values.rbac.create }}
apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SA_PASSWORD: {{ .Values.sql.saPassword | quote }}
{{- end }}
